[package]
name = "ic4"
version = "0.0.1"

edition.workspace = true
readme.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ic4-sys.workspace = true

once_cell.workspace = true

[features]
buildtime-bindgen = ["ic4-sys/bindgen"]
